exporter_name: products_csv
exporter_type: csv
collection: products
fields: 
  - header: "gid"
    path: "_gid"
  - header: "created_at"
    path: "_created_at"
  - header: "title"
    path: "_title"
  - header: "price"
    path: "_price"
  - header: "feedback"
    path: "_feedback"
  - header: "seller"
    path: "_seller"
